spring:
  kafka:
    consumer:
      group-id: "test-group"
      bootstrap-servers: "127.0.0.1:9092"
      enable-auto-commit: false
      auto-offset-reset: earliest
      isolation-level: read_committed

kafka:
  avro:
    consumer:
      schema-registry-url: "http://127.0.0.1:8081"
      specific-reader: true
      key-subject-name-strategy: io.confluent.kafka.serializers.subject.TopicNameStrategy
      value-subject-name-strategy: io.confluent.kafka.serializers.subject.TopicNameStrategy

demo:
  topic-name: "topicName"