spring:
  kafka:
    consumer:
      group-id: "test-group"
      bootstrap-servers: "127.0.0.1:9092"
      enable-auto-commit: false
      auto-offset-reset: earliest
      isolation-level: read_committed