spring:
  kafka:
    consumer:
      group-id: "test-group"
      key-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      bootstrap-servers: "127.0.0.1:9092"
      enable-auto-commit: false
      auto-offset-reset: earliest