spring:
  kafka:
    producer:
      acks: all
      key-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      bootstrap-servers: "127.0.0.1:9092"
      retries: 10

kafka:
  avro:
    producer:
      schema-registry-url: "http://127.0.0.1:8081"